### PR TITLE
Axel

### PR DESCRIPTION
**Pull request by hauduc**
Hi Stephan,

Sorry for the late pull request today, I ran into some unexpected problems with creating the tutorial this week as some files changed from last year and I had to go through everything again to make sure it worked.

Best,
Axel

### CODE REVIEW

**Comment by stephan-koenig** [comment]
Hi Axel,

I still see all the old commits from your original `axel` branch as part of the PR, and I do not understand why you encountered this problem. At the same time, you must check your work, and it takes only a second to see all the commits listed above to realize that something with your branch went wrong again.

Best,

Stephan

**Comment by hauduc** [comment]
Hi Stephan,

So sorry for the old commits still coming up. I had done ```git branch -d axel``` and ```git branch -D axel``` in RStudio, then deleted my directory and pulled the project from scratch. I think that after you merge #17 as well I deleted ```axel``` on the GitHub web interface. Quite confused as to why the old commits still pop up, but perhaps as a failsafe I can make new branches as ```axel-tutorialName```?

Apologies,
Axel

**Comment by stephan-koenig** [comment]
Hi Axel,

Hmm, that is strange. Usually, deleting the local repo and cloning a fresh copy gets rid of any peculiar git behaviour. Sure, try new branch names, though, e.g. `tutorial-5` and so on is sufficient. No need to prepend your name every time or append a more descriptive name. Do you maybe have time today or this week to meet briefly? I would like to briefly talk about what HTseq outputs the students will have created before the R section. It would also be great if you already have the output somewhere, then I can structure my teaching material around that data set. The meeting would also allow me to briefly see your git history on your local machine (maybe I can find something obvious). 

Best,

Stephan

**Comment by hauduc** [comment]
Hi Stephan,

Ok, will do. Perhaps when I deleted the branch locally it didn't sync because I needed to push or do something similar? That just came to my mind.

Would be happy to talk. Are you free tomorrow at 10am or 2:30pm? We could use my meeting room:
https://ubc.zoom.us/j/4257778888?pwd=QnlRc3U5Tkc1RURnZnVNeGpHbWpqQT09

I might have deleted my htseq outputs but I should be able to create them similarly from last year.

Best,
Axel

**Comment by hauduc** [comment]
Actually, would anytime between 2:30 and 5pm work?

Best,
Axel

**Comment by stephan-koenig** [comment]
Hi Axel,

Sure, let's meet at 3 pm on your meeting room!

See you then!

Stephan

**Comment by stephan-koenig** [comment]
Hi Axel,

Sure, let's meet at 3 pm on your meeting room!

See you then!

Stephan

-----
Dr. Stephan Koenig (He, Him, His<https://equity.ubc.ca/resources/gender-diversity/pronouns/>)
EDUCE Postdoctoral Teaching and Learning Fellow
Faculty of Science | Microbiology and Immunology | Hallam Lab
The University of British Columbia | Vancouver Campus | xʷməθkʷəy̓əm (Musqueam) Traditional Territory<https://www.musqueam.bc.ca/>
Biological Sciences Building
3106-6270 University Blvd | Vancouver BC | V6T 1Z3 Canada
Phone +1 (604) 827-4216
***@***.******@***.***>

On Oct 5, 2021, at 6:29 AM, Axel Hauduc ***@***.******@***.***>> wrote:

[CAUTION: Non-UBC Email]


Actually, would anytime between 2:30 and 5pm work?

Best,
Axel

**Pull request closed without merging**
